Fix for 2.49b release. Windows python26 would fail importing common modules like random. breaking ANT terrain tool and skin edge loop when a full python2.6 was not installed.
tested importing every module and found missing files...

__future__.py
_abcoll.py
abc.py
collections.py
functools.py
keyword.py
shlex.py
textwrap.py

note that modules 'sre' and 'genericpath' still fail to import.
these didnt reference any file but I dont think this should block release since none of our scripts use them.

* genericpath *
Traceback (most recent call last):
  File "Text.001", line 11, in <module>
  File "C:\b\install\win32-vc\python26.zip\genericpath.py", line 6, in <module>
  File "C:\b\install\win32-vc\python26.zip\os.py", line 63, in <module>
  File "C:\b\install\win32-vc\python26.zip\ntpath.py", line 191, in <module>
AttributeError: 'module' object has no attribute '_splitext'


* sre *
AttributeError: 'module' object has no attribute 'path'
Traceback (most recent call last):
  File "Text.001", line 2, in <module>
  File "C:\b\install\win32-vc\python26.zip\sre.py", line 7, in <module>
  File "C:\b\install\win32-vc\python26.zip\warnings.py", line 29, in _show_warning
  File "C:\b\install\win32-vc\python26.zip\warnings.py", line 39, in formatwarning
  File "C:\b\install\win32-vc\python26.zip\linecache.py", line 14, in getline
  File "C:\b\install\win32-vc\python26.zip\linecache.py", line 40, in getlines
  File "C:\b\install\win32-vc\python26.zip\linecache.py", line 82, in updatecache
AttributeError: 'module' object has no attribute 'path'