Gameengine compiles now with Makefiles. The gameplayer still has link problems because glsl routines defined in source/blender/src are being called in source/blender/blenkernel, which is generally frowned upon (the fix is either to move code from src --> blenkernel, or to create stubs.
The errors in particular are:

/tmp/soc-2007-maike/obj/linux-glibc2.5-x86_64/blender/blenkernel/libblenkernel.a
(material.o): In function `copy_material':
material.c:(.text+0x19c7): undefined reference to `glsl_active'
material.c:(.text+0x19d5): undefined reference to `glsl_create_materialtree'
/tmp/soc-2007-maike/obj/linux-glibc2.5-x86_64/blender/blenkernel/libblenkernel.a
(material.o): In function `init_material':
material.c:(.text+0x1ff6): undefined reference to `glsl_firstdraw'
/tmp/soc-2007-maike/obj/linux-glibc2.5-x86_64/blender/blenkernel/libblenkernel.a
(material.o): In function `init_def_material':
material.c:(.text+0x2195): undefined reference to `glsl_init_ghash'
/tmp/soc-2007-maike/obj/linux-glibc2.5-x86_64/blender/blenkernel/libblenkernel.a
(material.o): In function `init_material':
material.c:(.text+0x2007): undefined reference to `glsl_create_materialtree'
/tmp/soc-2007-maike/obj/linux-glibc2.5-x86_64/blender/blenkernel/libblenkernel.a
(scene.o): In function `set_scene_bg':
scene.c:(.text+0x585): undefined reference to `glsl_active'
scene.c:(.text+0x685): undefined reference to `glsl_firstdraw'
scene.c:(.text+0x699): undefined reference to `glsl_active'
scene.c:(.text+0x6b4): undefined reference to `glsl_free_all'
scene.c:(.text+0x694): undefined reference to `glsl_change_state'
scene.c:(.text+0x6af): undefined reference to `glsl_create_all'
collect2: ld returned 1 exit status